### ISSUE TITLE
Local setup instructions for database set up are incomplete

### ISSUE THREAD

**Issue by Shreya-7** [codethesaurus/docs#35]
`settings.py` has these two lines which try to reach the database specified in `DATABASE_URL` environment variable - which is not supposed to work for anybody doing local setup.
I was able to get it running because I recognised the URL being picked up as one of mine and found the corresponding lines to comment:
```
# db_from_env = dj_database_url.config(conn_max_age=500)
# DATABASES['default'].update(db_from_env)
```

It might not be immediately apparent, especially to thesaurus only contributors -- can we add this piece of instruction in the local setup docs? Happy to open the PR myself, if this seems like something that can be done.

**Comment by geekygirlsarah** [comment]
Hmm, I haven't seen this be a problem for me locally and haven't heard of this being an issue for anyone else. I know it's needed for production deploys to Heroku. Rather than comment it out, I'd probably rather wrap it in a `if env == PRODUCTION` type of thing so local installs won't try to run it. (which would be a PR needed against CT, not the docs)

**Comment by Shreya-7** [comment]
It's quite possible I faced this issue because I had that environment variable (`DATABASE_URL`) set for some other project, and the default database connection string got set as that value instead of `None` or something. I'm not really sure though - I followed all the instructions on the local setup guide.

Is the change you've suggested something we'd want to do?

**Comment by geekygirlsarah** [comment]
You're the only one that's run into this so far out of the few years this has been going (that I know of, anyway). I guess you could also add a note that says something along the lines of "Note: If you have a local `DATABASE_URL` environment variable, you will have to clear it to start Code Thesaurus." This also won't happen on Docker installs since they exist in their own space with their own environment variables. It'd just be for local installs.

**Comment by Shreya-7** [comment]
Cool, shall I add both of these things as notes on the local installs page? The user can either clear their environment variable or comment out those lines

**Comment by geekygirlsarah** [comment]
Don't edit the main project, just add a small note. I'd rather them remove the environment variable than edit/comment out code as it can accidentally get merged in and we don't want that.
